### ISSUE TITLE
API: RequisitionLine response format

### ISSUE THREAD

**Issue by joshxg** [openmsupply/msupply-rnr#123]
Currently the response for requisition do not have the stockClosing field.

In general this is calculated on the front-end, however it would be helpful for this field to be sent initialized to 0 for new requisitions.

**Comment by wlthomson** [comment]
Good idea. It needs to be saved, so agree It should also be initialised. Will add this to the beta milestone.

**Comment by wlthomson** [comment]
Fixed by #128. Closing.
