### ISSUE TITLE
Queries should be in dedicated file

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/msupply-rnr#132]
SQL queries should be in their own file. As they are related to the schema, this could be in the `config.js` file, or two separate files: `schema.js` and `queries.js`.

**Comment by joshxg** [comment]
I vote for one file called config

**Comment by wlthomson** [comment]
I think `schema` and `queries` as different files is a bit more modular, see what you think at PR time.

**Comment by joshxg** [comment]
O.K I agree.
