### ISSUE TITLE
API: Requisition Creation

### ISSUE THREAD

**Issue by joshxg** [openmsupply/msupply-rnr#133]
Currently the server in response to a post to /requisitions creates a requisition with the fields - id, masterlistId, storeid and date.

It would be helpful if other fields were also completed server-side.

- storeName 
- supplierName
- status (wp)
- type (request)
- orderType (sent from client - 'regular' or 'emergency')
- daysToSupply (30)
- comment ( '' )
- enteredByName (from jwt)
- serialNo. (uuid for now?)
- requesterReference ( '' )
- masterListName ( is sent by client ).

This would help tidy code for the getRequisition method in database.js, also.

**Comment by wlthomson** [comment]
Will do this now. I'm not sure what you mean by tidy up `getRequisition`, though? Although the data can  (and should) be generated when creating the requisition, it still has to get entered into the db, so as I see it getter behaviour will stay pretty much the same.
