### ISSUE TITLE
API: SQLite error on requisition endpoint - put

### ISSUE THREAD

**Issue by joshxg** [openmsupply/msupply-rnr#160]
Server logs an error on when a put request is sent to the requisitions endpoint

{ SQLError: SQL query UPDATE requisition
[2]                  SET supplierNameId = "undefined",
[2]                      date = "2019-01-23T11:00:00.000Z",
[2]                      status = "fn",
[2]                      type = "request",
[2]                      orderType = "regular",
[2]                      daysToSupply = 30,
[2]                      comment = "aaaaaa",
[2]                      enteredBy = "undefined",
[2]                      serialNo = 0d3ff200-1f75-11e9-b028-155484c2ffae,
[2]                      requesterReference = ""
[2]                  WHERE id = "0d3ff200-1f75-11e9-b028-155484c2ffae" threw error Error: SQLITE_ERROR: unrecognized token: "0d3ff200".

**Comment by wlthomson** [comment]
It looks like `RequisitionView` isn't PUTing the supplierNameId to the endpoint. One solution is to put this into the requisition, the other is for the backend to grab it from the session. Right now, the session option is the easiest, but later on we will probably have to change this. @joshxg Thoughts?

**Comment by joshxg** [comment]
Yeah, if we can just use the session. At the moment there is only one supplier, so def the easiest

**Comment by wlthomson** [comment]
OK will do that now.

**Comment by joshxg** [comment]
actually, maybe it would be easier to just send the suppliernameid with the requisition once it is created. In the future, the post for creating a requisition would contain masterlistid, suppliernameid, ordertypeid, so the suppliernameid will be getting sent and received anyway. I think this is just as easy and saves time later

**Comment by wlthomson** [comment]
That's true, but you still want to be able to update the supplier (e.g. if chose the wrong one by accident). So the PUT endpoint will still need to get that field, too. For now, I'll make it so PUT and POST both use the session for this. We can make an issue to change this if and when needed. Sound OK?

**Comment by joshxg** [comment]
if you just send the suppliernameid with the requisition, it will be saved in the requisition on the front end and automatically be sent back

**Comment by wlthomson** [comment]
Currently. the API design is that POSTing a requisition only returns the requisition ID, everything else has to be GETed later. Since the supplierNameId is sent by the front-end in the first place, it doesn't make much sense for the server to then relay information back that it doesn't change. When multiple suppliers are supported, these will have to be in the login JWT, and then an option will be available to choose from these, so the front-end will maintain these anyway. As said, for now will update the PUT and POSTs.
