### ISSUE TITLE
Test data json not moved when built

### ISSUE THREAD

**Issue by joshxg** [openmsupply/msupply-rnr#60]
After building, the app is run from the build folder rather than src. The test data json file does not get moved into build and must be manually moved before it can be used. It would be good if the json file is also copied into the build folder so manual moving isn't required. It would be an even greater step if the test data zip file is unzipped if the json doesn't exist in src.

**Comment by wlthomson** [comment]
Agree with moving the test data to build. Probably not as helpful to automate the zip because it is password protected, so will require some amount of user intervention regardless.

**Comment by joshxg** [comment]
it may be better to have anonymized data that is freely available for use rather than password protected? Maybe something for the future, but having available data for testing would be really great, even after we are syncing with primary servers.

**Comment by wlthomson** [comment]
Agree. Something like a generator would be perfect, so we can generate datasets  with certain properties, e.g. differing sizes, distributions, missing rows etc. This would be useful for debugging and testing db query performance.
